# Circleci build file
# https://circleci.com/gh/cleanunicorn/flaterra

defaults: &defaults
  docker:
    - image: circleci/python:3.7.1
  working_directory: ~/flaterra

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            pip install --user -r requirements.txt

      - run:
          name: Black style check
          command: |
            pip3 install --user black
            python3 -m black --check ~/flaterra/

      - run:
          name: Ensuring that setup script is functional
          command: python3 setup.py install
          working_directory: ~/flaterra

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1

  pypi_release:
    <<: *defaults
    steps:
      - checkout:
          path: ~/flaterra
      - run:
          name: Verify Git tag vs. version
          command: python3 setup.py verify
      - run:
          name: Build
          command: python3 setup.py sdist
      - run:
          name: Deploy
          command: |
            sudo pip install --upgrade pip wheel setuptools twine
            twine upload dist/*

  sonar_analysis:
    <<: *defaults
    steps:
      - checkout:
          path: ~/flaterra

      - run:
          name: Install Sonarqube
          path: /tmp/
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
            unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - run:
          name: Analyze with Sonarqube
          path: ~/flaterra
          command: |
            /tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=cleanunicorn_flaterra -Dsonar.organization=cleanunicorn-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONARQUBE}

workflows:
  version: 2
  build_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - pypi_release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+(dev|)([0-9]+|))*/
          requires:
            - test
      - sonar_analysis:
          filters:
            tags:
              only: /.*/
          requires:
            - test
